[DDW-414]: Bump electron and related packages
input-output-hk/daedalus pull request #2206
Opened 2020-10-15 02:00 UTC by yakovkaravelov

This PR updated electron and related packages.
[Jira Ticket](https://jira.iohk.io/browse/DDW-414)

## Todos
- [x] Update electron and related packages
- [x] Update nix shell scripts

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1602727073099700)

### App
- [x] Make sure app is working properly

### Storybook
- [x] Make sure all the stories are working properly

## Testing Summary

### Test suite
The test suite executed for this PR can be found on [this link](https://docs.google.com/spreadsheets/d/1tc2XvC0naspHw7UPbuw4pOZdwclaE4l-Fz-sQLcGL9Q/edit?usp=sharing).

### Fixed
1 - Blank screen is displayed. Reported [here](https://github.com/input-output-hk/daedalus/pull/2190#issuecomment-701950733).

2 -  Wallets can't be restored or created. Reported [here](https://github.com/input-output-hk/daedalus/pull/2190#issuecomment-703544034)

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2020-10-15 13:11 UTC, ManusMcCole commented
Hi @yakovkaravelov. When attempting to open the state directory path in Daedalus Diagnostics Screen the Open button would not work and I got this error in the console. See <a href="https://drive.google.com/file/d/1IT1iiz7nr_N--2rRXmocp6ua64iQjVpA/view?usp=sharing">here</a>

2020-10-15 14:51 UTC, ManusMcCole commented
Hi @yakovkaravelov. I added two more items to my comment above and I updated the test summary in the PR Description

2020-10-28 16:22 UTC, ManusMcCole commented
Hi @yakovkaravelov . Here is the QA Summary for build 14590.

**Still Pending** Issues. I was able to reproduce the 2 issues below on the new build

1 - There is an error in the console "State snapshot log file creation failed". This is caused by downloading logs. The logs downloaded succesfully success message is still shown. See <a href="https://drive.google.com/file/d/1wdBNuEeR_eNdRgLeXi7g8u33FzYZG02F/view?usp=sharing">here</a>

2 - Not able to run Daedalus on Linux. Attempted with both MainNet and TestNet. The only log available is this [see log](https://drive.google.com/file/d/1f7muVgzwwSc8ZKWZvT72HezsqdGRwbdt/view?usp=sharing)


 *Fixed *
1 - When attempting to open the state directory path on Windows in Daedalus Diagnostics Screen the Open button would not work and I got this electron error in the console. See <a href="https://drive.google.com/file/d/1IT1iiz7nr_N--2rRXmocp6ua64iQjVpA/view?usp=sharing">here</a>
Same issue on [Mac](https://drive.google.com/file/d/1VBJLBK2E5V5-333IQXCo3Wy0zWpnDBPK/view?usp=sharing)

2 - When attempting to send a transaction that is not possible because I do not have enough funds an incorrect error message "Cannot calculate fees while there are pending transactions" is displayed. There are no pending transactions in the wallet. See <a href="https://drive.google.com/file/d/1WHGOlu1FlQY_sj-Sj2JnudL731WrfDzy/view?usp=sharing">here</a> 

**Test Document**
For test document see [here](https://docs.google.com/spreadsheets/d/14r6z_m58VQkzWM6TWE1l41A5OjxOVjoxeCtLcdK2Rck/edit#gid=287361067)

2020-10-29 08:47 UTC, nikolaglumac commented
> 1 - On Mac and Windows.There is an error in the console "State snapshot log file creation failed". This is caused by downloading logs. The logs downloaded succesfully success message is still shown. See here

@ManusMcCole does this happen on all networks (Mainnet, Testnet, Shelley QA, Flight...)?

cc @yakovkaravelov

2020-10-29 09:14 UTC, ManusMcCole commented
Hi @yakovkaravelov and @nikolaglumac. For "1 - On Mac and Windows.There is an error in the console "State snapshot log file creation failed". This is caused by downloading logs. The logs downloaded succesfully success message is still shown. See <a href="https://drive.google.com/file/d/1wdBNuEeR_eNdRgLeXi7g8u33FzYZG02F/view?usp=sharing">here</a>" this issue happens on all Networks on Windows and Mac. I cannot test Linux as it will not launch

Also for "2 - When attempting to send a transaction that is not possible because I do not have enough funds an incorrect error message "Cannot calculate fees while there are pending transactions" is displayed. There are no pending transactions in the wallet. See <a href="https://drive.google.com/file/d/1WHGOlu1FlQY_sj-Sj2JnudL731WrfDzy/view?usp=sharing">here</a>" it was marked as fixed but today now I notice sometimes there is a delay where Daedalus takes a good few seconds to realise the user does not have enough UTXO for the transaction. The message calculating fees seems to have higher precedence over the "not enough ada.Try sending a smaller amount". See <a href="https://drive.google.com/file/d/1JWdAqnSoawu6Vqjx3p2knpx0-IO2K9WW/view?usp=sharing">video from newest build</a>. Im adding this to the report now

2020-10-29 09:17 UTC, nikolaglumac commented
> Also for "2 - When attempting to send a transaction that is not possible because I do not have enough funds an incorrect error message "Cannot calculate fees while there are pending transactions" is displayed. There are no pending transactions in the wallet. See here" it was marked as fixed but today now I notice sometimes there is a delay where Daedalus takes a good few seconds to realise the user does not have enough UTXO for the transaction. The message calculating fees seems to have higher precedence over the "not enough ada.Try sending a smaller amount". See video from newest build. Im adding this to the report now

@ManusMcCole I seriously doubt this is specific to this PR. Please test on other builds (2.4.0 release or develop builds) before adding this to the list of issues of this PR.

2020-10-30 10:16 UTC, mioriohk commented
Hi @yakovkaravelov . I have retested on build 15000 on all 3 platforms. Could replicate all the pending issues as listed in "Testing Summary" please see [here](https://github.com/input-output-hk/daedalus/pull/2206#issue-503751345)

2020-11-05 08:22 UTC, yakovkaravelov commented
The first issue was fixed.
So the following issue is only left.
```Not able to run Daedalus on Linux. Attempted with both MainNet and TestNet.```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Installing `daedalus-2.4.0-testnet-15056.bin` worked.
But after installing, running `daedalus-testnet` generated error as following.
![image](https://user-images.githubusercontent.com/6207747/98214609-8f9d3000-1efb-11eb-8feb-e00cdbfa1bfe.png)

* Couldn't figure out what `The updater file is missing!` error message means.
* Based on error message `/bin/electron: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory`, tried to install missing dependencies.
Referenced this: https://github.com/xorilog/docker-telegram/pull/13/files
But those packages were already installed.

I suspect there is some error in `default.nix`, `linux.nix`, `shell.nix` or `yarn2nix.nix`.

2020-11-05 08:24 UTC, nikolaglumac commented
> The first issue was fixed.
> So the following issue is only left.
> `Not able to run Daedalus on Linux. Attempted with both MainNet and TestNet.`
> 
> ```
> Installing `daedalus-2.4.0-testnet-15056.bin` worked.
> But after installing, running `daedalus-testnet` generated error as following.
> ![image](https://user-images.githubusercontent.com/6207747/98214609-8f9d3000-1efb-11eb-8feb-e00cdbfa1bfe.png)
> 
> * Couldn't figure out what `The updater file is missing!` error message means.
> * Based on error message `/bin/electron: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory`, tried to install missing dependencies.
> Referenced this: https://github.com/xorilog/docker-telegram/pull/13/files
> But those packages were already installed.
> 
> I suspect there is some error in `default.nix`, `linux.nix`, `shell.nix` or `yarn2nix.nix`.
> ```

@cleverca22 @disassembler can you guys please help us with this?

2020-11-05 08:26 UTC, yakovkaravelov commented
@cleverca22 @disassembler Need some help for this.

2021-02-01 19:55 UTC, nikolaglumac commented
@disassembler @cleverca22 this one has to be dealt with in February. We count on your support.

2021-06-17 08:50 UTC, miorsufianiohk requested changes
Installation error observed when attempting to install build 18347 on Mac Testnet. See [screenshot](https://drive.google.com/file/d/1A_o2gLnu-nyN7_-cCYIWbs5OzS-kJkX8/view?usp=sharing)

2021-06-17 20:05 UTC, gabriela-ponce commented
@danielmain On build 18349, Daedalus doesn't restart after selecting "Blank screen fix".
Check [this](https://drive.google.com/file/d/1EIaHLFfGe_k73uphw1Plzfq8zbC1n_Qj/view?usp=sharing) video for the current build (I didn't record it, but there were no errors in the console). [This](https://drive.google.com/file/d/1UTxpfj8D396J-rSDlCjsL8MBkAeyUyqA/view?usp=sharing) is how it works on the last build on develop branch. 
It reproduces in Ubuntu 20.04 and Windows 10.

2021-06-18 09:20 UTC, ManusMcCole commented
Hi @danielmain. Ledger Nano S and Ledger X are not connecting to Daedalus on Mac. The “Connect your device and enter…..” message remained after the device is physically connected and unlocked. No errors on the console Daedalus just never recognises the device. Even after many attempts will not connect even once. Connected succcesfully on Linux. I have tested on Mac I will check now on Windows to see if the errors exists there too

2021-06-18 09:42 UTC, ManusMcCole commented
Hi @danielmain. It would not connect either on windows. this time an error did appear on the [console](https://drive.google.com/file/d/1P7IPBesSqwk5FcDIIgoN0gdNRU3gpMDU/view?usp=sharing). Daedalus would recognise device and ask to launch cardano application on your device but does not proceed after the app is launched

2021-06-18 10:34 UTC, danielmain commented
> @danielmain On build 18349, Daedalus doesn't restart after selecting "Blank screen fix".
> Check [this](https://drive.google.com/file/d/1EIaHLFfGe_k73uphw1Plzfq8zbC1n_Qj/view?usp=sharing) video for the current build (I didn't record it, but there were no errors in the console). [This](https://drive.google.com/file/d/1UTxpfj8D396J-rSDlCjsL8MBkAeyUyqA/view?usp=sharing) is how it works on the last build on develop branch.
> It reproduces in Ubuntu 20.04 and Windows 10.

Hi @gabriela-ponce thank you for your time testing this PR. The issue is now fixed in Build #18358. You should now be able to restart Daedalus with "Blank screen fix". See [Video](https://drive.google.com/file/d/11p3ck4YZ5P7Q3hfK7EHnIT8ee_B8k30k/view?usp=sharing):

2021-06-18 11:14 UTC, ManusMcCole commented
Hi @danielmain unfortunately the same issues have arisen again even after i upgraded to Ledger firmware 2.0.0 and also Cardano App 2.3.2 [Firmware status](https://drive.google.com/file/d/1s2Y0K5P7qBSl9XiNHFPM-bOXmyeC6DLE/view?usp=sharing). I Performed a clean install of Daedalus and state directory was deleted

Same error on windows as before here is the new [screenshot](https://drive.google.com/file/d/1-HyzG1l5iZrjJYa4vt4TXWAzHho8pG08/view?usp=sharing)

On Mac it is once again The “Connect your device and enter…..” message remains after the device is physically connected and unlocked.

2021-06-18 12:54 UTC, gabriela-ponce commented
@danielmain on the build 18358:

- Each time I close Daedalus it reopens by itself. Happens on all platforms. Check [this](https://drive.google.com/file/d/1yl5qeuSwIMbwhLBHc81aYJWtcvr2Vk8l/view?usp=sharing) video.
- Daedalus restarts after choosing "Blank screen fix", but the fix is disabled (it should look like [this](https://drive.google.com/file/d/1nOaDXqQ2qsZJhX8cIpslm_KD86zGnULX/view?usp=sharing)). Check [this](https://drive.google.com/file/d/1wb3QmWzZYhF2vvzqMwz_GQoa22bJbJ-D/view?usp=sharing) video.
- I was able to reproduce the same issues that @ManusMcCole reported for Ledger S on macOS and Windows using firmware version 2.0.0 and Cardano app 2.3.2.

2021-07-05 15:26 UTC, gabriela-ponce commented
@danielmain I checked the two first issues from [this](https://github.com/input-output-hk/daedalus/pull/2206#issuecomment-864016992) comment on the latest build (18473). Here are my findings:

- When you select "Blank screen fix", the Cardano node stops, but Daedalus doesn't restart. If you close it manually after this, it would restart, but the "Blank screen fix" won't be enabled. Check [this](https://drive.google.com/file/d/1FDrT7c8yEouqXNAIJrTPklS3qgC7uZHR/view?usp=sharing) video.
This reproduces on all platforms. We'll continue the regression and updating [this](https://docs.google.com/spreadsheets/d/1PUtK8AR9DTnklfHPNhDlCAt3eKkLsJ7wLChiytActQI/edit?usp=sharing) document. We'll let you know if there are other findings on the latest build.

2021-07-15 08:47 UTC, nikolaglumac commented
@danielmain let's make sure to revert this commit before merging: https://github.com/input-output-hk/daedalus/pull/2206/commits/e49537bf8b5daabe909ba9506f257c1162c4744b

2021-07-19 18:45 UTC, gabriela-ponce commented
@danielmain On build 18620 I can reproduce the following issue:

- After "Blank screen fix" is active, it can't be deactivated. Check [this](https://drive.google.com/file/d/1sbCyJDrtvTZpJcPM--agUByxnFG92J95/view?usp=sharing) video. Happens on all platforms.

2021-07-30 16:36 UTC, danielmain commented
After a deep research by debugging all affected products, I can summarize what is the call stack that produces the crash after closing Daedalus.

The problem start as follows:

### daedalus
- source/main/index.js:117
- source/main/windows/main.js:68
- source/main/ipc/index.js:50
- source/main/ipc/getHardwareWalletChannel.js:443 => **TransportNodeHid.listen(observer)**

### hw-transport-node-hid
- packages/hw-transport-node-hid/src/TransportNodeHid.ts:79 => listenDevices(
- packages/hw-transport-node-hid/src/listenDevices.ts:74 => usb.on("attach", attachDetected)

### node-usb
- usb.js:515 => usb._enableHotplugEvents()
- src/node_usb.cc:179 => hotplugThis.Reset(info.This().As<Napi::Object>(), 1);

If we disable the line src/node_usb.cc:179 we dont have a crash

## Test by yourself with different Electron versions
Parallelly I created a simple electron project that only loads node-usb and it crashes using electron 9-13 but not in electron 8

`[https://github.com/danielmain/electron-crash-using-usb](https://github.com/danielmain/electron-crash-using-usb)`

I created two bugs on Electron and in node-usb repos respectively

https://github.com/electron/electron/issues/30347
https://github.com/tessel/node-usb/issues/438

We can wait until we get a feedback or we create our own node-usb version, disable that line and re-tests all HW scenarios

@nikolaglumac @tomislavhoracek

2021-08-24 18:22 UTC, gabriela-ponce commented
@danielmain I checked the pending issues on build 18857. Here are the results:

- The error in BigSur no longer reproduces after closing Daedalus, nice job 🎉 
- The "Blank screen fix" issue is ok now, but the state is not persisted after closing Daedalus. To clarify: In this build If you choose "Blank screen fix", when you close and reopen Daedalus, it is off again. In the version from production, it's a state that doesn't change until you deactivate it.

2021-08-25 08:18 UTC, nikolaglumac commented on source/main/environment.js
> -const isBlankScreenFixActive = includes(process.argv.slice(1), '--safe-mode');
@danielmain please revert this.

2021-08-25 08:18 UTC, nikolaglumac commented on source/main/utils/safeExitWithCode.js
> -    app.exit(exitCode);
@danielmain please revert this.

2021-08-31 19:04 UTC, gabriela-ponce commented
@danielmain Here is a list of new issues on the latest build. I'll update the issue summary, but most of the previous issues no longer reproduce:

**macOS:**
- The error "transaction confirmation failed" is displayed if you create a transaction for Ledger S and connect the device after. Check [this](https://drive.google.com/file/d/1AY-sUIDrzKap88KuPp78N2oquTNdJJtY/view?usp=sharing) screenshot.

**Windows:**
- Pair a Ledger S device, wait for it to sync and unlock it. Create a transaction without connecting the device, you'll see that Daedalus asks to "Run cardano app" instead of "Connect the Ledger S". A lot of errors are visible in the console. Check [this](https://drive.google.com/file/d/13ENOwBgwAofb82fq-4y42YQoAsICve9O/view?usp=sharing) screenshot.
Note: If you connect the device at this stage, you still can confirm the transaction.

- [This issue is intermittent, I couldn't get a proper video yet]. When trying to delete a Ledger S wallet, an error on the console is displayed. The process of deletion can take a while and if you restart Daedalus, the wallet is still there. Check [this](https://drive.google.com/file/d/1-Z2WYHAMrb44xRw_WNr4mggGvIn4ghLp/view?usp=sharing) screenshot to see the error.

**All:**
- I was able to reproduce the same issue that Mior mentioned [here](https://github.com/input-output-hk/daedalus/pull/2206#issuecomment-906480448). If you try to move all the funds from a Shelley wallet, you'll get an error message that says there are no enough ADA to cover the fees. Check these screenshots: [transaction](https://drive.google.com/file/d/13ENOwBgwAofb82fq-4y42YQoAsICve9O/view?usp=sharing), [error](https://drive.google.com/file/d/1y76cO5NADvXxzzCi3LSGrJ6dHAn2wwN2/view?usp=sharing). It does not happen in all the Shelley wallets, I think it can be related to wallets that have rewards.

2021-09-03 07:51 UTC, nikolaglumac commented
@miorsufianiohk @gabriela-ponce @ManusMcCole @danielmain when can we expect this one to be approved?

2021-09-06 21:40 UTC, gabriela-ponce commented
@nikolaglumac So far [the regression is ok.](https://docs.google.com/spreadsheets/d/1ZEvSxJWwwNQA5Grqs_b6Wh3qkt0sfijGNsOwYQSFHfI/edit?usp=sharing) I found a couple of issues that still reproduce from previous builds on macOS:

- If you connect the device after opening the confirmation dialog, you get the message "An error occurred". Check [screenshot](https://drive.google.com/file/d/14LzELWuwnfl8_lUA_Va6qJNaE56KSoMi/view?usp=sharing).

- Can't confirm 2 transactions in a row without disconnecting the device. On the second transaction, the device won't be detected. Check [screenshot](https://drive.google.com/file/d/1gEmoSXxtDki981e2zzRzBfBUWMT7Hq4R/view?usp=sharing).

@miorsufianiohk can you please confirm if you reproduce this in Ledger Nano X?

2021-09-07 07:52 UTC, nikolaglumac commented
@gabriela-ponce @miorsufianiohk @ManusMcCole @dmitrii-gaico please re-test all HW scenarios on all platforms and lets get some numbers 🙏

2021-09-07 09:07 UTC, miorsufianiohk commented
> @miorsufianiohk can you please confirm if you reproduce this in Ledger Nano X?
@gabriela-ponce , I could confirm that for Nano X on MacOS this happened -> If you connect the device after opening the confirmation dialog, you get the message "An error occurred". [See screenshot](https://drive.google.com/file/d/1rHAP2uh_Lf2njWwRduzHCntHPtPZg7gX/view?usp=sharing).

2021-09-10 21:26 UTC, gabriela-ponce commented
@nikolaglumac @danielmain Just finished checking the[ Ledger S cases](https://docs.google.com/spreadsheets/d/1ZEvSxJWwwNQA5Grqs_b6Wh3qkt0sfijGNsOwYQSFHfI/edit?usp=sharing) on build 19005 for all platforms, and these are the findings:

- Windows and Linux are ok.
- [These](https://github.com/input-output-hk/daedalus/pull/2206#issuecomment-913862570) issues still reproduce in macOS. The second issue doesn't happen all the time.

2021-09-12 12:38 UTC, nikolaglumac commented
> @nikolaglumac @danielmain Just finished checking the[ Ledger S cases](https://docs.google.com/spreadsheets/d/1ZEvSxJWwwNQA5Grqs_b6Wh3qkt0sfijGNsOwYQSFHfI/edit?usp=sharing) on build 19005 for all platforms, and these are the findings:
> 
> * Windows and Linux are ok.
> * [These](https://github.com/input-output-hk/daedalus/pull/2206#issuecomment-913862570) issues still reproduce in macOS (BigSur). The second issue doesn't happen all the time.

@gabriela-ponce is the same issue reproducible on develop or latest release (4.3.1)?

2021-09-13 11:25 UTC, miorsufianiohk commented
> @gabriela-ponce is the same issue reproducible on develop or latest release (4.3.1)?
I am unable to reproduce Gabriela's findings for Nano S on both latest release 4.3.1 and latest develop 19015. Currently testing latest build for this PR. Will report later 👍

2021-09-13 11:27 UTC, dmitrii-gaico commented
> > @nikolaglumac @danielmain Just finished checking the[ Ledger S cases](https://docs.google.com/spreadsheets/d/1ZEvSxJWwwNQA5Grqs_b6Wh3qkt0sfijGNsOwYQSFHfI/edit?usp=sharing) on build 19005 for all platforms, and these are the findings:
> > 
> > * Windows and Linux are ok.
> > * [These](https://github.com/input-output-hk/daedalus/pull/2206#issuecomment-913862570) issues still reproduce in macOS (BigSur). The second issue doesn't happen all the time.
> 
> @gabriela-ponce is the same issue reproducible on develop or latest release (4.3.1)?

We have validated both scenarios at MacOS Catalina/BigSur | 4.3.1 current release and latest develop. In all cases issues are NOT reproducible.

2021-09-13 11:30 UTC, nikolaglumac commented
Perfect 👌 
Please approve the PR once ready and I will merge it 🚀

2021-09-13 11:32 UTC, nikolaglumac approved these changes
A true masterpiece 💯 
Amazing work @danielmain 🎉

2021-09-13 14:42 UTC, miorsufianiohk approved these changes
LGTM. Tested on 19020 Testnet with Nano S on Win, BigSur, Catalina and Linux 👍

2021-09-13 14:46 UTC, dmitrii-gaico approved these changes

2021-09-14 06:25 UTC, merged