[DDW-496] Scrollable dialogs improvement
input-output-hk/daedalus pull request #2285
Opened 2020-12-22 11:32 UTC by yakovkaravelov

This PR improved scrollable dialogs layout
[Jira Ticket](https://jira.iohk.io/browse/DDW-496)

## Todos
- [x] Improve scrollable dialogs layout

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1608636165081400)

### App
- [x] Check all the scrollable dialogs and make sure they are matching with wireframe. https://zpl.io/VkABvQg

## Test Cases

## Testing Summary

English
![image](https://user-images.githubusercontent.com/6207747/102884142-f328e180-4405-11eb-8e9d-d9e6903f376d.png)
![image](https://user-images.githubusercontent.com/6207747/102884160-fc19b300-4405-11eb-9d9e-a79e0517aced.png)

Japanese
![image](https://user-images.githubusercontent.com/6207747/102884211-13f13700-4406-11eb-98d2-e4b335e8b320.png)
![image](https://user-images.githubusercontent.com/6207747/102884236-1fdcf900-4406-11eb-83d9-bd9920a50fd2.png)

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2020-12-23 11:26 UTC, DeeJayElly approved these changes
Looks ok @yakovkaravelov

2020-12-28 12:23 UTC, a-rukin requested changes
Fix issues in PR description

2020-12-31 10:34 UTC, mioriohk commented
Looks OK to me on build 15751. Need to double check with Yakov which dialogs are exactly scrollable and which aren't.

2020-12-31 10:54 UTC, a-rukin commented
> Looks OK to me on build 15751. Need to double check with Yakov which dialogs are exactly scrollable and which aren't.

This rule should be applied to all dialogs. As they can eventually become scrollable with a bigger content. 
This is a feature of dialog as a component, not just a fix for a spot with wrong padding...

2020-12-31 11:07 UTC, mioriohk commented
> > Looks OK to me on build 15751. Need to double check with Yakov which dialogs are exactly scrollable and which aren't.
> 
> This rule should be applied to all dialogs. As they can eventually become scrollable with a bigger content.
> This is a feature of dialog as a component, not just a fix for a spot with wrong padding...

Thanks for the clarification @a-rukin . Apart from the design issues that you have found, looks OK to me so far. I am going to do another round of testing on this.

2021-01-04 15:45 UTC, DeeJayElly approved these changes
Looks ok @yakovkaravelov gj !!!

2021-01-08 14:49 UTC, gnpf approved these changes

2021-01-08 17:04 UTC, nikolaglumac commented
@gnpf what about these? 
<img width="798" alt="Screenshot 2021-01-08 at 18 04 28" src="https://user-images.githubusercontent.com/376611/104043370-fb419900-51db-11eb-94d3-89f63277dbc5.png">

2021-01-08 18:09 UTC, nikolaglumac commented
We will not be merging this one without @a-rukin's approval.

2021-01-08 18:12 UTC, gnpf commented
@nikolaglumac @yakovkaravelov The issues mentioned in the description are fixed, except this:

>  Restore dialog has "steps" part scrollable.

Check [this screenshot.](https://drive.google.com/file/d/1Eagc7_rwXZ4OIAWV55hUAIXJkrbuWx2h/view?usp=sharing)

2021-01-11 09:22 UTC, a-rukin commented
@nikolaglumac @gnpf 
I'm sorry to say, but I can reproduce every issue from my list. 😢

2021-01-11 09:27 UTC, nikolaglumac commented
@yakovkaravelov please get on a call with @a-rukin and fix the remaining issues. Thanks!

2021-01-11 10:46 UTC, mioriohk commented
@yakovkaravelov Apart from what @a-rukin has found, here are the findings for build 15824:

Test case | Status | Comments
-- | -- | --
Scenario 2 | Failed | I could replicate the issue found by @gnpf [here](https://github.com/input-output-hk/daedalus/pull/2285#issuecomment-756915953). See [video here](https://drive.google.com/file/d/1rlmLWLj-64qkjvvRa-ENgwQm5UOxsNxT/view?usp=sharing)

2021-01-14 02:31 UTC, yakovkaravelov commented
@a-rukin @nikolaglumac Fixed the issues found by Sasha.
Please review again.
Thanks.

2021-01-14 08:57 UTC, a-rukin commented
@yakovkaravelov excellent!!
One small thing I found is that scrollbar [lost it's rounded corners](https://user-images.githubusercontent.com/2539345/104566934-48e85680-565f-11eb-92f6-b9b472014cb3.png)

2021-01-14 09:02 UTC, a-rukin requested changes

2021-01-14 09:02 UTC, a-rukin commented on source/renderer/app/components/widgets/Dialog.scss
> +      border-radius: 0;
@yakovkaravelov think this one is redundant

2021-01-14 12:08 UTC, mioriohk approved these changes
LGTM on build 15882. 👍

2021-01-14 13:57 UTC, nikolaglumac approved these changes
Great work @yakovkaravelov 👍

2021-01-14 15:20 UTC, a-rukin approved these changes
Great! Perfect! 👍

2021-01-14 15:31 UTC, merged