[DDW-452] Show ada amounts in other currencies
input-output-hk/daedalus pull request #2290
Opened 2021-01-04 17:42 UTC by daniloprates

This PR TBD.

## Todos

- [ ] Todo

## Screenshots

- Screenshot

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-01-04 19:40 UTC, matiwinnetou commented
There is also onchain metadata with currency data provided by me and stakepool: NUTS. 

https://nut.link/

2021-01-07 09:11 UTC, nikolaglumac commented
> There is also onchain metadata with currency data provided by me and stakepool: NUTS.
> 
> https://nut.link/

Thanks for the tip @matiwinnetou - much appreciated :-)

2021-02-11 07:34 UTC, darko-mijic commented
So excited to give this one a spin. 😺

2021-02-11 07:37 UTC, darko-mijic commented
@daniloprates, please add theming adjustents to todo list:
 
![image](https://user-images.githubusercontent.com/4280521/107611439-4a984080-6c44-11eb-9f2b-935a15e1b4fd.png)

2021-02-11 09:00 UTC, darko-mijic commented
@daniloprates, can you check if the refreshing of the UI component can be smoother? It removes the converted value before displaying the updated one. Maybe we should animate this somehow? @a-rukin?

2021-02-11 09:30 UTC, a-rukin commented
<img width="244" alt="image" src="https://user-images.githubusercontent.com/2539345/107619854-d752f680-6c64-11eb-8a3c-e0a07f31b972.png">
<img width="238" alt="image" src="https://user-images.githubusercontent.com/2539345/107619898-ed60b700-6c64-11eb-865d-2816d9daf81b.png">

@daniloprates can you make this "powered by" and "description" to be light font (now it's regular)

2021-02-11 09:31 UTC, a-rukin commented
<img width="727" alt="image" src="https://user-images.githubusercontent.com/2539345/107619956-023d4a80-6c65-11eb-8c4b-62e2c5b13fae.png">
something with centering here

2021-02-11 09:39 UTC, a-rukin commented
<img width="18" alt="image" src="https://user-images.githubusercontent.com/2539345/107620679-1e8db700-6c66-11eb-9455-2943ebdcce09.png">
@daniloprates hovering should make this one nontransparent. Maybe there is some alpha inside svg already?

2021-02-11 12:23 UTC, a-rukin commented
<img width="112" alt="image" src="https://user-images.githubusercontent.com/2539345/107635943-02494480-6c7d-11eb-9f8e-1ee6d0f96300.png">
Here is extra "g" in name

2021-02-11 12:36 UTC, a-rukin commented
> @daniloprates, can you check if the refreshing of the UI component can be smoother? It removes the converted value before displaying the updated one. Maybe we should animate this somehow? @a-rukin?

Can we not hide values while fetching?

2021-02-11 18:48 UTC, nikolaglumac requested changes
@daniloprates link to "CoinGecko" is not working - instead of opening the link in a browser, I get the dropdown focused...

![Screenshot 2021-02-11 at 19 47 39](https://user-images.githubusercontent.com/376611/107683603-0c316e80-6ca2-11eb-9c6c-6899bf9ab628.png)

2021-02-11 18:57 UTC, nikolaglumac requested changes
@daniloprates I have left only one comment in the code. Please check it out and also don't forget to add screenshots 🙏 
Thanks! Awesome work 💯

2021-02-11 18:57 UTC, nikolaglumac commented on source/renderer/app/api/utils/localStorage.js
> +    LocalStorageApi.unset(keys.CURRENCY_SELECTED);
@daniloprates shouldn't we here unset `keys.CURRENCY_ACTIVE`?

2021-02-11 20:19 UTC, gnpf commented
@daniloprates A few issues on build 16440:

1 - When the language is Japanese, the text next to the gear is displayed in English. Check [this](https://drive.google.com/file/d/1wfjCac4t6NmXV615EeVbRgrvQqeMd4rv/view?usp=sharing) screenshot.

2 - The balance is displayed as 0.00 while syncing. Check [this](https://drive.google.com/file/d/1spLAEfR2QR8G1s-LYR_Q5YetvgfDQsM3/view?usp=sharing) screenshot. Maybe this should also display "-" while the wallet is syncing?

3 - If I disable the option of seeing other currencies, it would be enabled again after a restart. Check [this](https://drive.google.com/file/d/1L_GHHK7x2PrdaGPIkxVqwBW2G-agfG7h/view?usp=sharing) video.

I'm adding some test scenarios to this PR, could you review them, please?

2021-02-12 08:09 UTC, nikolaglumac commented
We need to implement some more text copy changes: https://docs.google.com/document/d/1YrqW0yW3O4p7bARMERDYK3Pz5a9bRIFMUQ5GZ0eaR5w/edit#heading=h.jo1dsl3gyz08

2021-02-12 08:42 UTC, nikolaglumac commented
> We need to implement some more text copy changes: https://docs.google.com/document/d/1YrqW0yW3O4p7bARMERDYK3Pz5a9bRIFMUQ5GZ0eaR5w/edit#heading=h.jo1dsl3gyz08

Implemented in: https://github.com/input-output-hk/daedalus/pull/2290/commits/933a4d0d0b385b4349dddc1944fa24cb48c2aa5b

2021-02-12 08:57 UTC, nikolaglumac commented
> @daniloprates A few issues on build 16440:
> 
> 1 - When the language is Japanese, the text next to the gear is displayed in English. Check [this](https://drive.google.com/file/d/1wfjCac4t6NmXV615EeVbRgrvQqeMd4rv/view?usp=sharing) screenshot.
> 
> 2 - The balance is displayed as 0.00 while syncing. Check [this](https://drive.google.com/file/d/1spLAEfR2QR8G1s-LYR_Q5YetvgfDQsM3/view?usp=sharing) screenshot. Maybe this should also display "-" while the wallet is syncing?
> 
> 3 - If I disable the option of seeing other currencies, it would be enabled again after a restart. Check [this](https://drive.google.com/file/d/1L_GHHK7x2PrdaGPIkxVqwBW2G-agfG7h/view?usp=sharing) video.
> 
> I'm adding some test scenarios to this PR, could you review them, please?

@gnpf I can confirm that all these issues have been fixed in the latest build.

2021-02-12 09:03 UTC, nikolaglumac approved these changes
Amazing job @daniloprates 🎉

2021-02-12 09:27 UTC, a-rukin commented
@daniloprates this block requires "line-height:22px;" for explanation text 
without
<img width="542" alt="image" src="https://user-images.githubusercontent.com/2539345/107750805-92df5d80-6d2d-11eb-864b-ded519d03188.png">
with
<img width="543" alt="image" src="https://user-images.githubusercontent.com/2539345/107750877-ad193b80-6d2d-11eb-9d22-85542c3e02a3.png">

2021-02-12 09:29 UTC, a-rukin commented
<img width="194" alt="image" src="https://user-images.githubusercontent.com/2539345/107751084-f9fd1200-6d2d-11eb-8cee-8a17649f4277.png">
"Converts as" too far to the top now

2021-02-12 09:31 UTC, a-rukin commented
<img width="692" alt="image" src="https://user-images.githubusercontent.com/2539345/107751262-3c265380-6d2e-11eb-9dc5-3e9564574054.png">
this padding should be 20px (can't diagnost why it adds a bit more)

2021-02-12 09:35 UTC, ManusMcCole approved these changes
Great job @daniloprates 👍

2021-02-12 09:48 UTC, mioriohk approved these changes
LGTM. Tested on 16454. Great job @daniloprates 👍

2021-02-12 10:26 UTC, a-rukin approved these changes
🧙

2021-02-12 10:26 UTC, merged