[DDW-559] Implement delegation deposit from coin selection
input-output-hk/daedalus pull request #2332
Opened 2021-02-02 13:38 UTC by tomothespian

This PR introduces dynamic delegation deposit from coin selection.

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Open Delegation wizard with Trezor and Ledger HW wallets and check if fees are correctly calculated. If you already delegated with that wallet fees are regular and without deposit. Otherwise deposit is included

**_NOTE:_** _Pay attention to fees. When you want to delegate HW for the very first time, a delegation deposit is also included in the fees. After that deposit is not charged anymore.
Since you already delegated with your HW, to check if a deposit is included (fees > 2ADA) you will need to wipe your devices. When you will wipe devices ensure that you have initial mnemonics on safe (from first device setup) so you can access your funds after this test. Then set a new device (wipe) with different mnemonics. After that, you will get a new fresh wallet / device. Create a new wallet in Daedalus with wiped device and  you will see that balance is 0ADA._

---

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-02-03 11:42 UTC, nikolaglumac requested changes
@tomothespian please implement requested changes 🙏

2021-02-03 11:42 UTC, nikolaglumac commented on source/renderer/app/api/api.js
> +      let delegationDepositSum = 0;
@tomothespian please change this to "totalDeposits" and push it above the line where you calculate `transactionFee`: https://github.com/input-output-hk/daedalus/blob/728ec6e0978bb4fd34e21d61fb29abc925768ba5/source/renderer/app/api/api.js#L965-L967

Then you will have a nicer way to calculate the fee:
```
const fee = new BigNumber(totalInputs - totalOutputs - totalDeposits).dividedBy(
    LOVELACES_PER_ADA
);
```

2021-02-03 11:42 UTC, nikolaglumac commented on source/renderer/app/api/api.js
> +      if (response.deposits) {
@tomothespian please use a nicer way to sum up all deposits. Something like:

```
const totalDeposits = map(response.deposits || [], (deposit) => {...
```

2021-02-03 11:42 UTC, nikolaglumac commented on source/renderer/app/api/api.js
> +      // On first wallet delegation fee also includes a deposit
@tomothespian we don't need this comment anymore...

2021-02-03 12:13 UTC, gnpf commented
Works as expected on Ledger Nano S 💯

2021-02-03 14:05 UTC, mioriohk commented
LGTM on Ledger Nano X. Good job @tomothespian 👍 . Tested on 16219

2021-02-03 14:09 UTC, ManusMcCole approved these changes
All good for Trezor Model T on 16219 👍

2021-02-03 14:32 UTC, tomothespian commented
@nikolaglumac Code Improved!

@gnpf @ManusMcCole @mioriohk Can you test one more time just in case

2021-02-03 14:47 UTC, nikolaglumac approved these changes
Great work @tomothespian 💯

2021-02-03 14:57 UTC, nikolaglumac requested changes

2021-02-03 14:57 UTC, nikolaglumac commented on source/renderer/app/api/api.js
> +        totalInputs - totalOutputs
@tomothespian please use BigNumber to deduct outputs from inputs.

2021-02-03 14:57 UTC, nikolaglumac commented on source/renderer/app/api/api.js
> +        totalInputs - totalOutputs - totalDeposits
@tomothespian please use BigNumber to deduct deposits and outputs from inputs.

2021-02-04 14:16 UTC, mioriohk approved these changes
LGTM on Ledger Nano X. Good job @tomothespian 👍 . Tested on 16268

2021-02-04 15:24 UTC, gnpf approved these changes

2021-02-04 16:03 UTC, ManusMcCole approved these changes

2021-02-04 16:30 UTC, nikolaglumac approved these changes
Great work @tomothespian 💯

2021-02-04 16:30 UTC, merged