Feature/ddw 521 display transaction metadata
input-output-hk/daedalus pull request #2338
Opened 2021-02-03 20:56 UTC by DominikGuzei

This PR adds support for rendering transaction metadata:

## Todos

- [ ] Add Japanese translations
- [ ] Discuss rendering implementation (vs. JSON.stringify as alternative)

## Screenshots

![CleanShot 2021-02-03 at 21 47 49](https://user-images.githubusercontent.com/172414/106807842-e7b61080-6669-11eb-920d-710ceaabb081.gif)

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] transactions with metadata should have a "show unmoderated metadata" link and do not render the metadata by default
- [ ] when clicking on "show unmoderated metadata" the warning + link should be replaced by the metadata itself
- [ ] transactions with / without metadata should render correctly

---

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-02-03 21:21 UTC, nikolaglumac requested changes
@DominikGuzei I don't see the metadata which is visible on the Explorer 😢 
TX: https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=4dc5093d26fdd8d82ba30615eda72d96b80ed28d3750d916ab1d3ab6fee4b4b3

Testnet Explorer: 
![Screenshot 2021-02-03 at 22 20 25](https://user-images.githubusercontent.com/376611/106811045-10400980-666e-11eb-8ce4-fa5bb30177d7.png)

Testnet Daedalus:
![Screenshot 2021-02-03 at 22 20 36](https://user-images.githubusercontent.com/376611/106811058-1504bd80-666e-11eb-8310-d32e9761a9d6.png)

I have also picked up these errors:
![Screenshot 2021-02-03 at 22 19 14](https://user-images.githubusercontent.com/376611/106811084-1c2bcb80-666e-11eb-9ccd-9db9901065ca.png)

2021-02-04 14:25 UTC, DominikGuzei commented
@nikolaglumac these issues should be fixed now 👍

2021-02-04 16:38 UTC, nikolaglumac commented
@DominikGuzei please work with @darko-mijic on getting the final text copy and Japanese translations. We need this merged by the end of the day tomorrow 🙏 

PS. @darko-mijic this PR is important for Fund3!

2021-02-04 17:57 UTC, gnpf commented
@DominikGuzei Here are a few issues on the latest build (16293):

- When the metadata is expanded, all the data is showed outside the container. Check [this screenshot](https://drive.google.com/file/d/1HSOyo88YF1K9TrVuxIlmtV0hS8nCrmK9/view?usp=sharing).
- The space between "Transaction metadata" and the rest of the content is smaller than the rest. Check [this screenshot](https://drive.google.com/file/d/1p8De87z35rUFJb9hfJakPlBZgNnc2hsB/view?usp=sharing).

2021-02-04 21:07 UTC, DominikGuzei commented
@gnpf the second issue is fixed 👍 
I could not reproduce "When the metadata is expanded, all the data is displayed outside the container" on the latest build – can you re-test?

2021-02-05 10:10 UTC, nikolaglumac commented on source/renderer/app/api/utils/request.js
>              const parsedBody = JSON.parse(body);
@DominikGuzei shouldn't we use `JSONBigInt` here too?

2021-02-05 10:36 UTC, nikolaglumac commented
@gnpf @a-rukin @ManusMcCole @mioriohk please test this one 🙏

2021-02-05 10:36 UTC, nikolaglumac commented on source/renderer/app/api/utils/request.js
>              const parsedBody = JSON.parse(body);
I have added this change.

2021-02-05 10:50 UTC, nikolaglumac commented
> When the metadata is expanded, all the data is displayed outside the container. Check this screenshot.

@gnpf I have fixed this ☝️

2021-02-05 11:06 UTC, a-rukin commented
![image](https://user-imag@DominikGuzei ubusercontent.com/2539345/107026023-37f0b800-67bb-11eb-8543-b243c3f80bfa.png)
@DominikGuzei this padding feels a bit smaller than 20px 
Is this an illusion?

2021-02-05 12:18 UTC, nikolaglumac commented
> ![image](https://user-images.githubusercontent.com/2539345/107026106-4e970f00-67bb-11eb-8e9b-583e688e2ca4.png)
> 
> @DominikGuzei this padding feels a bit smaller than 20px
> Is this an illusion?

I have checked this. This is an illusion. It is all OK!

2021-02-05 12:25 UTC, nikolaglumac approved these changes
Nice work @DominikGuzei 👍

2021-02-05 12:28 UTC, a-rukin approved these changes
LGTM

2021-02-05 12:36 UTC, gnpf approved these changes
Looks good 🎉

2021-02-05 12:38 UTC, merged

2021-02-05 12:42 UTC, DominikGuzei commented
Great work everyone 🎉