[DDW-522] Display fee and deposit on transaction details and delegation modal
input-output-hk/daedalus pull request #2339
Opened 2021-02-04 08:44 UTC by yakovkaravelov

This PR displayed fee and deposit info on transaction details and delegation confirmation modal
[Jira Ticket](https://jira.iohk.io/browse/DDW-522)

## Todos
- [x] Display fee and deposit info on transaction details panel
- [x] Display fee and deposit info on delegation confirmation modal

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1612427519147700)

### App
- [x] Go to `Wallet` => `Transactions` and expand transaction items and make sure `fee` is shown in any outgoing or delegation transaction item and `deposit` is shown in any delegation or undelegation transaction item
- [x] Go to `Staking` => `Stake pools` => `Delegation` wizard and continue to confirmation step and make sure `fee` and `deposit` values are shown

## Screenshots

### English
![image](https://user-images.githubusercontent.com/6207747/106866882-fb2d9f80-669a-11eb-9b93-64cdcd7fdb63.png)
![image](https://user-images.githubusercontent.com/6207747/106866934-08e32500-669b-11eb-9686-8da397938fad.png)

### Japanese
![image](https://user-images.githubusercontent.com/6207747/106866988-1ac4c800-669b-11eb-8447-09ed1cea5fdf.png)
![image](https://user-images.githubusercontent.com/6207747/106867064-29ab7a80-669b-11eb-9e77-60da7beeb993.png)

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-02-04 11:51 UTC, mioriohk approved these changes
LGTM. Good job @yakovkaravelov 👍 . Tested on 16267

2021-02-04 12:35 UTC, ManusMcCole approved these changes

2021-02-05 10:36 UTC, nikolaglumac commented
@a-rukin please test this one

2021-02-05 10:38 UTC, a-rukin requested changes

2021-02-05 10:39 UTC, nikolaglumac requested changes

2021-02-05 10:39 UTC, nikolaglumac commented on source/renderer/app/themes/daedalus/incentivized-testnet.js
> +    '--theme-transactions-list-item-highlight-color': '#ea4c5b',
@yakovkaravelov please change this colour to `#ea4c5b `

2021-02-05 10:47 UTC, nikolaglumac approved these changes

2021-02-05 10:48 UTC, merged

2021-02-06 16:44 UTC, nikolaglumac commented
@yakovkaravelov please add screenshots of the delegation wizard which includes the deposit 🙏