[DDW-550] Hover not working properly on the first tile in the delegation center
input-output-hk/daedalus pull request #2386
Opened 2021-02-19 10:12 UTC by yakovkaravelov

This PR adjusted hover PopOver styles on the first tile in the delegation center screen
[Jira Ticket](https://jira.iohk.io/browse/DDW-550)

## Todos
- [x] Adjust hover PopOver styles on the first tile in the delegation center screen

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1613729133296700)

### App
- [x] Go to `Staking` => `Delegation Center`, hover the first tile and make sure the PopOver styles are correct

### Test Cases

## Screenshots

### English
![image](https://user-images.githubusercontent.com/6207747/108490585-e5120880-7270-11eb-8b50-d4b5fe685769.png)

### Japanese
![image](https://user-images.githubusercontent.com/6207747/108490628-efcc9d80-7270-11eb-874d-1b2df4897d14.png)

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-02-19 12:24 UTC, ManusMcCole approved these changes
Looks good 👍

2021-02-19 12:50 UTC, nikolaglumac requested changes
@yakovkaravelov the tooltip's tip (triangle) is not correctly positioned when the number of characters in the stake pool ticker is different than 4...

![Screenshot 2021-02-19 at 13 48 51](https://user-images.githubusercontent.com/376611/108506592-57a6d680-72b9-11eb-8638-ec15b537e138.png)
![Screenshot 2021-02-19 at 13 48 53](https://user-images.githubusercontent.com/376611/108506593-583f6d00-72b9-11eb-98e8-322f3b914a85.png)

Please implement better positioning for it as the char length and the width of chars in the ticker can vary...

2021-02-22 07:14 UTC, nikolaglumac commented
@yakovkaravelov please let us know once this is ready to be tested again...

2021-02-22 13:36 UTC, yakovkaravelov commented
@nikolaglumac @daniloprates @ManusMcCole @miorsufianiohk Please review/test, thanks.

2021-02-22 13:42 UTC, nikolaglumac commented
@DominikGuzei please review this one 🙏

2021-02-23 09:59 UTC, nikolaglumac commented on source/renderer/app/components/staking/delegation-center/WalletRow.js
> +    const {
@yakovkaravelov can you please extract this logic into a separate method which then gets invoked in the `componentDidUpdate`?
That would be cleaner...

2021-02-23 10:23 UTC, nikolaglumac approved these changes
👌

2021-02-23 12:47 UTC, ManusMcCole approved these changes

2021-02-23 13:06 UTC, merged