[DDW-579] Undelegated wallet shown as delegated on "Delegation center" screen
input-output-hk/daedalus pull request #2404
Opened 2021-02-25 14:29 UTC by yakovkaravelov

This PR fixed delegated stake pool status on Delegation Center screen
[Jira Ticket](https://jira.iohk.io/browse/DDW-579)

## Todos
- [x] Fix delegated stake pool status on Delegation Center screen

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1614262917027700)

### App
- [x] Go to `Staking` => `Delegation Center` and make sure delegated stake pool statuses of wallets are properly shown up

## Screenshots

### English
![image](https://user-images.githubusercontent.com/6207747/109167399-b9e55880-774b-11eb-956b-dae1f0772756.png)

### Japanese
![image](https://user-images.githubusercontent.com/6207747/109167443-c49fed80-774b-11eb-8b2e-9491e7c95cd2.png)

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-02-26 07:55 UTC, nikolaglumac commented
@yakovkaravelov please merge latest develop.

2021-02-26 10:56 UTC, tomislavhoracek requested changes
@yakovkaravelov Nice job.
I left just one comment. 
P.S. Why this is changed if you didn't touch translations? Can you check this please
`source/renderer/app/i18n/locales/defaultMessages.json`
And also merge latest `develop` branch and fix conflicts

2021-02-26 10:56 UTC, tomislavhoracek commented on source/renderer/app/components/staking/delegation-center/WalletRow.js
> +      get(foundDelegation, 'status') === WalletDelegationStatuses.NOT_DELEGATING
@yakovkaravelov isolate this to e.g. `const isDelegating`

2021-02-26 11:31 UTC, yakovkaravelov commented
> @yakovkaravelov Nice job.
> I left just one comment.
> P.S. Why this is changed if you didn't touch translations? Can you check this please
> `source/renderer/app/i18n/locales/defaultMessages.json`
> And also merge latest `develop` branch and fix conflicts

@tomislavhoracek `defaultMessage.json` can be changed when there is line number change regarding translation definitions even if there is no change in translation resources.
It happens after running `yarn manage:translations`

2021-02-26 11:57 UTC, miorsufianiohk commented
@yakovkaravelov  Unable to test as not able to undelegate on Yoroi due to transaction issue on testnet. See [screenshot](https://drive.google.com/file/d/1yUmGZjQYmhDEkgLLIPRBGsJmmlHPRk1u/view?usp=sharing)

2021-02-26 12:56 UTC, tomislavhoracek approved these changes
@yakovkaravelov code looks good now 👍

2021-02-26 14:40 UTC, darko-mijic commented
Reviewing this now with Trezor HW wallet on the mainnet...

2021-02-26 14:55 UTC, darko-mijic commented
![image](https://user-images.githubusercontent.com/4280521/109315522-eaf88280-784a-11eb-9343-118de0a840c7.png)
Works great. IOHK Trezor 2 is now undelegated.

2021-02-26 14:55 UTC, darko-mijic approved these changes

2021-02-26 14:58 UTC, gabriela-ponce approved these changes
I undelegated in Yoroi and the changes are visible in Daedalus for [Ledger S](https://drive.google.com/file/d/1InJt5NhW5dGHR4ZwVgnIm6EPblDpODx8/view?usp=sharing) and [software wallets](https://drive.google.com/file/d/1nimqHZypmd2x8JdCp5pvuUKt6uu7kgFp/view?usp=sharing).

2021-02-26 15:02 UTC, miorsufianiohk approved these changes
Tested with software wallet on Yoroi testnet and Daedalus testnet. Good work @yakovkaravelov 👍

2021-02-27 13:24 UTC, nikolaglumac approved these changes

2021-02-27 13:25 UTC, merged