[DDW-589] Fix native tokens UI/UX issues
input-output-hk/daedalus pull request #2422
Opened 2021-03-02 10:43 UTC by yakovkaravelov

This PR fixed text overlapping issue on native token input field.
[Jira Ticket](https://jira.iohk.io/browse/DDW-589)

## Todos
- [x] Fix text overlapping issue on native token input field.

## Testing Checklist
- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1614681327128000)

### App
- [x] Go to `Wallet` => `Send`, click on `Add token` button to generate token input field and make sure token input field text is not overlapped with addon button text when filling in big value

## Screenshots

### English
![image](https://user-images.githubusercontent.com/6207747/109636726-eddcc700-7b19-11eb-9558-526879ec8ad8.png)

### Japanese
![image](https://user-images.githubusercontent.com/6207747/109636807-08af3b80-7b1a-11eb-9d4d-9cf79a7cf1b7.png)

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes and shows some screenshots or animated GIFs of important UI changes
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-03-02 11:32 UTC, miorsufianiohk approved these changes
LGTM. Great work @yakovkaravelov . Tested on 16889

2021-03-02 11:33 UTC, ManusMcCole approved these changes

2021-03-02 17:38 UTC, nikolaglumac commented on source/renderer/app/components/wallet/WalletSendForm.js
> +                    <AssetTokenInput
@yakovkaravelov please rename this component to `AssetInput`

2021-03-02 17:40 UTC, nikolaglumac commented on source/renderer/app/components/wallet/WalletSendForm.js
> +                      receiverFormField={formFields.receiver}
@yakovkaravelov we should not pass the whole `receiverFormField`. It should be enough to pass just the individual `assetField` and the `assetsDropdown`.

2021-03-02 17:48 UTC, nikolaglumac requested changes
@yakovkaravelov can we apply the same dynamic width calculation for the ada amount field too? 🙏 

![Screenshot 2021-03-02 at 18 46 52](https://user-images.githubusercontent.com/376611/109691445-bc024980-7b87-11eb-82ed-f000109d06d2.png)

2021-03-02 17:48 UTC, nikolaglumac commented
@darko-mijic let's also update this tooltip text copy so that it doesn't mention other assets in case user is sending only ada.

![Screenshot 2021-03-02 at 18 48 00](https://user-images.githubusercontent.com/376611/109691637-ef44d880-7b87-11eb-9d8f-b4ff22acc9db.png)

2021-03-04 08:35 UTC, nikolaglumac commented
@darko-mijic can you please help us with https://github.com/input-output-hk/daedalus/pull/2422#issuecomment-789090959

2021-03-04 10:16 UTC, yakovkaravelov commented
This is finished. Please review, @gabriela-ponce @tomislavhoracek Thanks.

2021-03-04 17:15 UTC, nikolaglumac approved these changes
Great work 🎉

2021-03-04 18:23 UTC, gabriela-ponce approved these changes
Looks good 🎉

2021-03-04 18:35 UTC, merged