[DDW-691] Implement custom browser protocol to launch Daedalus
input-output-hk/daedalus pull request #2606
Opened 2021-06-28 12:08 UTC by tomislavhoracek

This PR introduces a custom browser protocol handlers that will launch Daedalus with specific set of parameters.

## Todos

- [ ] Todo

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-06-29 09:27 UTC, SebastienGllmt commented
Have you read https://github.com/cardano-foundation/CIPs/blob/master/CIP-0013/CIP-0013.md ? I noticed this isn't compatible with it

2021-06-29 12:05 UTC, tomislavhoracek commented
@SebastienGllmt This is still in progress and for now we just implemented a basic handler to check if it will work once the app is built. We will follow documentation once we are sure that our setup works properly. Thanks!
cc @nikolaglumac

2021-07-26 11:00 UTC, dmitrii-gaico commented
@tomislavhoracek @daniloprates Hello. QA team had a quick looks and please see the short report below.

Linux Testnet installed.
Daedalus open\closed. Chrome/Firefox - after hitting link a search is performed.(No Yoroi extension installed) 
Daedalus open\closed. Chrome/Firefox - after hitting link Yoroi is opened.(Yoroi extension installed) 

Windows Testnet and Mainnet installed.
Daedalus open\closed. Chrome/Firefox - after hitting link user suggested to open the Latest installed build. If the latest is Mainnet then it is suggested to open. However after confirming the Daedalus improperly started message is displayed. No Daedalus started.(No Yoroi extension installed) 
Daedalus open\closed. Chrome/Firefox - after hitting link Yoroi is opened.(Yoroi extension installed). 

Strange behavior related to Yoroi Extension :
If you have extension installed and you tried to run web link then it is opened in Yoroi. But once you uninstalled Yoroi extension Chrome is still trying to run the link as Extension but since it is gone Chrome is showing message that link is blocked and you can not see Open Daedalus dialog. In order to fix this you need to re-install Chrome at Windows \ Re-install and delete configs at Linux.

@input-output-hk/daedalus-qa Please add your findings for MacOS and anything related.

Thank you!

2021-07-26 15:31 UTC, daniloprates commented
@dmitrii-gaico my first test on testnet worked flawlessly. Do I need to do something else to reproduce the issue?

https://user-images.githubusercontent.com/1504716/127016332-ad91822c-4325-4199-8148-7af95ade0ced.mov

2021-07-26 15:38 UTC, daniloprates commented
@dmitrii-gaico if Daedalus is closed, chrome will open it, but it won't go to the send screen

https://user-images.githubusercontent.com/1504716/127017424-a753af13-aa85-4073-ae79-ee577bf3b56c.mov

2021-07-26 15:48 UTC, gabriela-ponce commented
Here are my findings on macOS BigSur on build 18656 with different browsers:

**Chrome with Yoroi extension**:
- Opens Daedalus after submitting the address. If Daedalus is open, [it creates the transaction](https://drive.google.com/file/d/1OpC5VUYVABH5FgjGlHu4QpWicL-AfEew/view?usp=sharing). If it's closed, [it only opens Daedalus, doesn't create the transaction](https://drive.google.com/file/d/1H0B1iibX09DiFwBXDV9kIrKwveWP-hLh/view?usp=sharing).

**Firefox without Yoroi extension**:
- Same results as Chrome when Daedalus is [closed](https://drive.google.com/file/d/1m4u6K-v6jqTEdRcpOicBvw5zWJobZoPM/view?usp=sharing) and [open](https://drive.google.com/file/d/18PLut0QxVWwXjCF9uhfbzejqzcv8siXC/view?usp=sharing).

**Safari without Yoroi extension**:
- Always performs a search, it doesn't ask to open Daedalus, no matter if it's [closed](https://drive.google.com/file/d/153eBtxByCC4k7hYsOk2lUPX8wqXCrYKc/view?usp=sharing) or [open](https://drive.google.com/file/d/1QqvBfYxDGkct82c8okeWPmwZ2yVN4iBY/view?usp=sharing).

**Opera without Yoroi extension**:
- Usually performs a search, it doesn't ask to open Daedalus, no matter if [closed](https://drive.google.com/file/d/1FmUQELtwfSa7xO33ZUTG__iYM_EddZuo/view?usp=sharing) or [open](https://drive.google.com/file/d/1FTkR6xHE76Yj82BN0N766xU1u2rE51wZ/view?usp=sharing). Sometimes [it opens Daedalus and created the transaction](https://drive.google.com/file/d/1rOm8UU9TGwqIcjHCNYJ7Ksb12bxxPHsz/view?usp=sharing), but not sure how to trigger this, need to investigate the configuration.

Will update with more information about other scenarios later.

2021-07-26 18:10 UTC, daniloprates commented
> @tomislavhoracek @daniloprates Hello. QA team had a quick look and please see the short report below.
> 
> **Linux Testnet installed.**
> Daedalus open\closed. Chrome/Firefox - after hitting link a search is performed.(No Yoroi extension installed)
> Daedalus open\closed. Chrome/Firefox - after hitting link Yoroi is opened.(Yoroi extension installed)
> 
> **Windows Testnet and Mainnet installed.**
> Daedalus open\closed. Chrome/Firefox - after hitting link user suggested to open the Latest installed build. If the latest is Mainnet then it is suggested to open. However after confirming the Daedalus improperly started message is displayed. No Daedalus started.(No Yoroi extension installed)
> Daedalus open\closed. Chrome/Firefox - after hitting link Yoroi is opened.(Yoroi extension installed).
> 
> **Strange behavior related to Yoroi Extension :**
> If you have extension installed and you tried to run web link then it is opened in Yoroi. But once you uninstalled Yoroi extension Chrome is still trying to run the link as Extension but since it is gone Chrome is showing message that link is blocked and you can not see Open Daedalus dialog. In order to fix this you need to re-install Chrome at Windows \ Re-install and delete configs at Linux.
> 
> @input-output-hk/daedalus-qa Please add your findings for MacOS and anything related.
> 
> Thank you!

@dmitrii-gaico could you paste the errors here?

2021-07-26 18:17 UTC, daniloprates commented
> @daniloprates @dmitrii-gaico Here are my findings on build 18656 with different browsers and platforms:
> 
> **macOS**
> 
> _Chrome with Yoroi extension_
> 
> * Opens Daedalus after submitting the address. If Daedalus is open, [it creates the transaction](https://drive.google.com/file/d/1OpC5VUYVABH5FgjGlHu4QpWicL-AfEew/view?usp=sharing). If it's closed, [it only opens Daedalus, doesn't create the transaction](https://drive.google.com/file/d/1H0B1iibX09DiFwBXDV9kIrKwveWP-hLh/view?usp=sharing).
> 
> _Firefox without Yoroi extension_
> 
> * Same results as Chrome when Daedalus is [closed](https://drive.google.com/file/d/1m4u6K-v6jqTEdRcpOicBvw5zWJobZoPM/view?usp=sharing) and [open](https://drive.google.com/file/d/18PLut0QxVWwXjCF9uhfbzejqzcv8siXC/view?usp=sharing).
> 
> _Safari without Yoroi extension_
> 
> * Always performs a search, it doesn't ask to open Daedalus, no matter if it's [closed](https://drive.google.com/file/d/153eBtxByCC4k7hYsOk2lUPX8wqXCrYKc/view?usp=sharing) or [open](https://drive.google.com/file/d/1QqvBfYxDGkct82c8okeWPmwZ2yVN4iBY/view?usp=sharing).
> 
> _Opera without Yoroi extension_
> 
> * Usually performs a search, it doesn't ask to open Daedalus, no matter if [closed](https://drive.google.com/file/d/1FmUQELtwfSa7xO33ZUTG__iYM_EddZuo/view?usp=sharing) or [open](https://drive.google.com/file/d/1FTkR6xHE76Yj82BN0N766xU1u2rE51wZ/view?usp=sharing). Sometimes [it opens Daedalus and created the transaction](https://drive.google.com/file/d/1rOm8UU9TGwqIcjHCNYJ7Ksb12bxxPHsz/view?usp=sharing), but not sure how to trigger this, need to investigate the configuration.
> 
> **Windows**
> 
> _All browsers, no Yoroi extension (Edge/Firefox/Opera/Chrome)_
> 
> * I was able to reproduce @dmitrii-gaico's findings. The browser asks to run Daedalus, but then there is an error system displayed mentioning that Daedalus was improperly started. It doesn't matter if Daedalus is closed or open. Check videos for [Edge](https://drive.google.com/file/d/1I-lTkPK8AUv94FKEpRbZPmOXCG9l7wca/view?usp=sharing), [Firefox](https://drive.google.com/file/d/1Tb-Mypm8BUCAToKkiTrtL6tNDkLc9i6C/view?usp=sharing), [Chrome](https://drive.google.com/file/d/1QFFHBUpJ7_HEVqvv_hrl4-cYpjdSVj_g/view?usp=sharing) and [Opera](https://drive.google.com/file/d/1oemhFxeFopaTiYf9QrpQPergizXVz6aI/view?usp=sharing).
> 
> _Chrome, with Yoroi extension_
> 
> * Maybe this is because Yoroi was installed after Daedalus (needs more investigation), but Yoroi is open instead of Daedalus. Check [video](https://drive.google.com/file/d/1gQKKQQTABXomHT0aGfjl-sWdz95JjG14/view?usp=sharing).
> 
> **Both Platforms**
> 
> _All browsers_
> Similar to what @dmitrii-gaico mentioned, no matter which one is the address on the url (mainnet, testnet), the browser would always try to open the last one that was executed. Check [this video.](https://drive.google.com/file/d/1jDoDDh2ZVfKRCqnQHmah9NoqUogiYry8/view?usp=sharing)

Thanks @gabriela-ponce!

2021-09-14 11:08 UTC, cleverca22 commented on source/main/index.js
> +      'xdg-mime default Daedalus*.desktop x-scheme-handler/web+cardano'
`xdg-mime default Daedalus*.desktop` must be ran with the right name for the cluster

the install script on linux does that for you, so the JS code doesnt need to run `xdg-mime` on linux

2022-03-29 14:57 UTC, michalrus requested changes

2022-03-29 14:57 UTC, michalrus commented on source/main/index.ts
> +  // TODO: this is unethical! user hostility – don’t touch my default programs, esp. when not asking me – @michalrus
I think this shouldn’t happen like that.

Right now, we re-associate `web+cardano://` to Daedalus on Windows and macOS on each application start, disregarding what the user might want.

Linux is set up correctly – associating `web+cardano://` once, in the installer.

I think we should do the same thing for Windows and macOS – associate *once* during installation, and never re-associate.

2022-03-29 14:58 UTC, michalrus commented on source/main/index.ts
> +  // TODO: this is unethical! user hostility – don’t touch my default programs, esp. when not asking me – @michalrus
/cc @angerman – a bit similar to auto-adding the app to macOS dock, which you found hostile – https://input-output-rnd.slack.com/archives/GJMEW8FV3/p1647944259851109?thread_ts=1647861796.476749&cid=GJMEW8FV3

2022-03-29 15:09 UTC, michalrus commented on source/renderer/app/components/wallet/WalletSendForm.tsx
> +  resetCustomProptocolParams: Function | null | undefined;
typo: pro**p**tocol

2022-03-30 07:47 UTC, michalrus commented on source/main/index.ts
> +  safeExitWithCode(0);
I’m really not sure why this change was introduced – if `safeWithExitCode` for second instance will just `app.exit(0)` anyway… (and had to be modified to do just that, or else there are errors about `log.transports.file.stream` being undefined.

2022-05-04 08:41 UTC, michalrus requested changes
9 tests are failing in `yarn test:jest`: 
```
FAIL  source/renderer/app/components/wallet/WalletSendForm.spec.tsx (6.566 s)
```

2023-06-27 06:33 UTC, marcin-mazurek commented
Closing as agreed with @tomislavhoracek on Slack.

2023-06-27 06:33 UTC, closed without merging