Added jest and couple of unit tests for DDW-706
input-output-hk/daedalus pull request #2630
Opened 2021-07-23 11:50 UTC by danielmain

This PR CHANGES.

Add Jest library and Unit Tests to the new added functions introduced in branch DDW-706

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-07-26 12:01 UTC, DominikGuzei requested changes

2021-07-26 14:37 UTC, DominikGuzei commented on __tests__/wallet-utils.specs.js
> +// As a user using a shelly wallet when sending ADA and the balance after the transactions remains < 10 ADA, the following Warning message is displayed in the send confirmation dialog
Let's avoid too long lines like this

2021-07-26 14:42 UTC, DominikGuzei commented on __tests__/assets.specs.js
> +  it('Function hasTokenLeftAfterTransaction returns false in case after the transaction tokes are left in the wallet', () => {
Typo in word "tokes" -> should be "tokens"

2021-07-29 07:30 UTC, closed without merging

2021-07-29 11:59 UTC, DominikGuzei commented
@danielmain do you know why this was closed? :D

2021-07-29 12:28 UTC, danielmain commented
@DominikGuzei long story short, I did not know merging the parent branch would close automatically this PR. Let me recreate it now. By the way, your suggestions are in the code now :)