[DDW-744] Adjust font for Delegation Center info message
input-output-hk/daedalus pull request #2680
Opened 2021-09-21 09:54 UTC by mchappell

This PR CHANGES.
Fixed font used in delegation center staking unavailable while syncing message
## Todos

- [ ] Change scss used in staking unavailable to use correct fonts

## Screenshots

- Screenshot
<img width="1350" alt="Screenshot 2021-09-21 at 10 52 45" src="https://user-images.githubusercontent.com/7581002/134150593-0f9a0270-01f5-43fa-8b24-c59995a9afe7.png">
<img width="1345" alt="Screenshot 2021-09-21 at 10 53 03" src="https://user-images.githubusercontent.com/7581002/134150610-07c46f6b-2750-48e8-ac0d-63428a6dadb0.png">

---

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

## Review Checklist

### Basics

- [ ] PR has been assigned and has appropriate labels (`feature`/`bug`/`chore`, `release-x.x.x`)
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR has default-sized Daedalus window screenshots or animated GIFs of important UI changes:
  - [ ] In English
  - [ ] In Japanese
- [ ] CHANGELOG entry has been added to the top of the appropriate section (*Features*, *Fixes*, *Chores*) and is linked to the correct PR on GitHub
- [ ] Automated tests: All acceptance and unit tests are passing (`yarn test`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *development* build (`yarn dev`)
- [ ] Manual tests (minimum tests should cover newly added feature/fix): App works correctly in *production* build (`yarn package` / CI builds)
- [ ] There are no *flow* errors or warnings (`yarn flow:test`)
- [ ] There are no *lint* errors or warnings (`yarn lint`)
- [ ] There are no *prettier* errors or warnings (`yarn prettier:check`)
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] UI changes look good in all themes (Alexander Rukin)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality
- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with flow
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing
- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review
- [ ] Merge the PR
- [ ] Delete the source branch
- [ ] Move the ticket to `done` column on the YouTrack board
- [ ] Update Slack QA thread by marking it with a green checkmark

2021-09-21 10:10 UTC, danielmain approved these changes
Great job Michael

2021-09-21 14:28 UTC, dmitrii-gaico approved these changes

2021-09-21 15:02 UTC, miorsufianiohk approved these changes
LGTM. Great work @mchappell 👍

2021-09-22 08:59 UTC, nikolaglumac requested changes
Nice work @mchappell - I have left just one little

2021-09-22 08:59 UTC, nikolaglumac commented on CHANGELOG.md
> +- Fixed font used for unavailable staking while updating messages ([PR 2680](https://github.com/input-output-hk/daedalus/pull/2680))
@mchappell please put this line to the top of the "Fixes" column

2021-09-22 09:19 UTC, nikolaglumac approved these changes

2021-09-22 09:20 UTC, merged