[DDW-966] Improve RTS splash message
input-output-hk/daedalus pull request #2901
Opened 2022-02-28 15:10 UTC by przemyslaw-wlodek

This PR adds better description to the RTS splash screen message. It includes instruction how to enable/disable RTS flags.

## Screenshots

![image](https://user-images.githubusercontent.com/17825044/156006130-ca3f4c11-0d91-40ef-9a1f-07a65a78c8c6.png)
![image](https://user-images.githubusercontent.com/17825044/156008983-08cb7c71-42f4-451f-bc6e-2fa9e7c8f419.png)

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1646061063178959)
- [ ] Test

---

## Review Checklist

### Basics

- [x] PR assigned to the PR author(s)
- [x] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [x] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [x] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [x] PR link is added to a Jira ticket, ticket moved to In Review
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes
- [x] PR contains screenshots (in case of UI changes)
- [x] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [x] There are no missing translations (running `yarn manage:translations` produces no changes)
- [x] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [x] Japanese text changes are proofread and approved (Junko Oda)
- [x] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

2022-02-28 15:25 UTC, alexander-rukin approved these changes
looks ok

2022-02-28 15:25 UTC, alexander-rukin commented on source/renderer/app/components/knownIssues/RTSFlagsRecommendationOverlay/RTSFlagsRecommendationOverlay.scss
> +        margin-bottom: 0;
isn't "p + p" work anymore?

2022-02-28 16:29 UTC, marcin-mazurek approved these changes
![image](https://user-images.githubusercontent.com/6684554/156020348-e8adef5c-bce8-43de-b242-05d57c720636.png)

2022-03-03 10:42 UTC, szymonmaslowski requested changes
Just have two small recommendations

2022-03-03 10:42 UTC, szymonmaslowski commented on CHANGELOG.md
> +- Improved RTS flags splash screen message ([PR 2901](https://github.com/input-output-hk/daedalus/pull/2901))
Please move this line to the top of the section

2022-03-03 10:42 UTC, szymonmaslowski commented on storybook/stories/news/AlertsOverlay.stories.tsx
> +    <RTSFlagsRecommendationOverlay onConfirm={noop} onClose={noop} />
Please use the `action` from storybook actions plugin ;)

2022-03-08 09:37 UTC, ManusMcCole approved these changes
Looks good to me 👍

2022-03-08 13:44 UTC, merged