Use flake-compat with cardano-wallet master.
input-output-hk/daedalus pull request #2951
Opened 2022-04-07 10:43 UTC by jbgi

2022-04-08 11:03 UTC, michalrus commented
The blocks start syncing on all 3 platforms, so I would assume this is correct.

Thank you, @jbgi! :bow: 

/cc @danielmain 

-----

![Screenshot-20220408-124401](https://user-images.githubusercontent.com/4366292/162423419-b158f3f8-07d5-488f-b6de-659dd33e44f9.png)
![Screenshot-20220408-125030](https://user-images.githubusercontent.com/4366292/162423423-028ddaef-e41a-45b5-beb7-3e820ab3fb6a.png)
![Screenshot-20220408-130135](https://user-images.githubusercontent.com/4366292/162423428-5dca0536-f12a-4447-96c0-37a3fdb3aea2.png)

2022-04-08 11:03 UTC, michalrus approved these changes

2022-04-19 12:28 UTC, danielmain approved these changes

2022-04-19 13:09 UTC, michalrus commented on default.nix
> +    x86_64-darwin = macos.intel;
There is only `macos.silicon` in cardano-wallet’s `hydraJobs` – which is being added one line below:

```
% pwd
/home/mw/Development/cardano-wallet

% git rev-parse @
d3a5ad4b8e283b46ae5eb699eb68f4f4ce88de55

% nix repl
Welcome to Nix 2.4. Type :? for help.

nix-repl> :lf .
Added 24 variables.

nix-repl> outputs.hydraJobs.macos.<TAB><TAB>
outputs.hydraJobs.macos.intel    outputs.hydraJobs.macos.silicon
```

2022-04-21 11:11 UTC, michalrus requested changes
Wallet syncing doesn’t work:
* https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1650457031248759?thread_ts=1650363534.113549&cid=GGKFXSKC6
* https://input-output-rnd.slack.com/archives/GGKFXSKC6/p1650455427271789?thread_ts=1650366876.403389&cid=GGKFXSKC6

Erroring out with `Cannot read property 'quantity' of undefined` in API responses.

2022-05-02 07:26 UTC, michalrus approved these changes
Thank you to all involved!

2022-05-04 10:58 UTC, dmitrii-gaico approved these changes

2022-05-04 11:06 UTC, danielmain approved these changes

2022-05-04 11:06 UTC, merged