[DDW-1076] Wait validation completion
input-output-hk/daedalus pull request #2962
Opened 2022-04-14 18:17 UTC by renanvalentin

This PR ...

## Todos

- [ ] TODO

## Screenshots

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

## Review Checklist

### Basics

- [ ] PR assigned to the PR author(s)
- [ ] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [ ] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [ ] PR link is added to a Jira ticket, ticket moved to In Review
- [ ] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [ ] PR has a good description that summarizes all changes
- [ ] PR contains screenshots (in case of UI changes)
- [ ] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [ ] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

2022-04-18 18:54 UTC, lucas-barros approved these changes

2022-04-19 11:31 UTC, shawnbusuttil approved these changes

2022-04-26 13:16 UTC, marcin-mazurek requested changes

2022-06-24 12:29 UTC, gabriela-ponce approved these changes
Nice job 🎉

2022-06-30 13:17 UTC, marcin-mazurek commented on source/renderer/app/components/wallet/WalletSendForm.spec.tsx
> +    const mock = jest
sounds good

2022-06-30 13:19 UTC, marcin-mazurek commented on source/renderer/app/components/wallet/WalletSendForm.spec.tsx
> +jest.mock(
Makes sense - not ideal but I think fixing this properly would increase the scope of this bug fix significantly.

2022-06-30 13:21 UTC, marcin-mazurek approved these changes

2022-06-30 13:21 UTC, marcin-mazurek commented on source/renderer/app/components/wallet/WalletSendForm.spec.tsx
> +        expect(totalAmountConfirmation).toHaveTextContent(expectedTotalAmount);
The formating seems to be broken?

2022-07-01 14:43 UTC, merged