[DDW-1152] Fix general stories
input-output-hk/daedalus pull request #3064
Opened 2022-10-19 11:26 UTC by VanessaPC

The General stories of Storybook were either not handling the state of some props in storybook, or knobs weren't working. So now they should display the behaviour they are expected to have.
[Jira ticket](https://input-output.atlassian.net/browse/DDW-1152)

## Todos
- [x] Build storybook with ` yarn storybook:build`
- [x] Run storybook `yarn storybook`
- [x] Find the General components and check the three of them. 
- [x] Pass an story, or mock an store and pass the props appropriately

## Screenshots

<img width="919" alt="Screenshot 2022-10-19 at 11 17 33" src="https://user-images.githubusercontent.com/4052063/196677500-281cf74d-7b68-4526-b18d-5076a0432a7e.png">
<img width="930" alt="Screenshot 2022-10-19 at 11 17 40" src="https://user-images.githubusercontent.com/4052063/196677505-c228e717-df66-4c51-96c0-dea21d2f7c99.png">
<img width="922" alt="Screenshot 2022-10-19 at 11 17 46" src="https://user-images.githubusercontent.com/4052063/196677508-67e09695-9d44-4998-8b89-9d6368f22063.png">
<img width="924" alt="Screenshot 2022-10-19 at 11 17 54" src="https://user-images.githubusercontent.com/4052063/196677511-d9bbe124-6ed2-40ca-a652-7ed3f8952fe2.png">
<img width="920" alt="Screenshot 2022-10-19 at 11 18 01" src="https://user-images.githubusercontent.com/4052063/196677514-22dc3e3c-c8f3-4442-b8c7-57ca2a257d6d.png">
<img width="904" alt="Screenshot 2022-10-19 at 11 24 23" src="https://user-images.githubusercontent.com/4052063/196677519-11734cd8-6e38-4bed-ba02-706a7162d260.png">
<img width="913" alt="Screenshot 2022-10-19 at 11 24 30" src="https://user-images.githubusercontent.com/4052063/196677521-f871db05-aa0e-48b3-a725-9f14acb81906.png">
<img width="910" alt="Screenshot 2022-10-19 at 11 24 38" src="https://user-images.githubusercontent.com/4052063/196677525-8bf0f7a5-9213-4a89-8f11-a0a19024d791.png">
<img width="909" alt="Screenshot 2022-10-19 at 11 24 45" src="https://user-images.githubusercontent.com/4052063/196677527-4695bcbc-c727-43ec-8adc-77aca76a7be3.png">
<img width="917" alt="Screenshot 2022-10-19 at 11 17 28" src="https://user-images.githubusercontent.com/4052063/196677493-11ef3dcb-3f4c-466e-9540-3e2961cef78c.png">

## Testing Checklist

- [Slack QA thread](https://input-output-rnd.slack.com/messages/GGKFXSKC6)
- [ ] Test

---

- [ ] Make sure the dropdowns in General > General work 
- [ ] Make sure the switches on General > Wallets and General> Security work.

## Review Checklist

### Basics

- [x] PR assigned to the PR author(s)
- [x] `input-output-hk/daedalus-dev` and `input-output-hk/daedalus-qa` assigned as PR reviewers
- [ ] If there are UI changes, Alexander Rukin assigned as an additional reviewer
- [ ] All visual regression testing has been reviewed (assign `run Chromatic` label to PR to trigger the run)
- [x] PR has appropriate labels (`release-vNext`, `feature`/`bug`/`chore`, `WIP`)
- [x] PR link is added to a Jira ticket, ticket moved to In Review
- [x] PR is updated to the most recent version of the target branch (and there are no conflicts)
- [x] PR has a good description that summarizes all changes
- [x] PR contains screenshots (in case of UI changes)
- [x] CHANGELOG entry has been added to the top of the appropriate section (_Features_, _Fixes_, _Chores_) and is linked to the correct PR on GitHub
- [ ] There are no missing translations (running `yarn manage:translations` produces no changes)
- [ ] Text changes are proofread and approved (Jane Wild / Amy Reeve)
- [ ] Japanese text changes are proofread and approved (Junko Oda)
- [ ] Storybook works and no stories are broken (`yarn storybook`)
- [ ] In case of dependency changes `yarn.lock` file is updated

### Code Quality

- [x] Important parts of the code are properly commented and documented
- [ ] Code is properly typed with typescript types
- [ ] React components are split-up enough to avoid unnecessary re-renderings
- [ ] Any code that only works in main process is neatly separated from components

### Testing

- [ ] New feature/change is covered by acceptance tests
- [ ] New feature/change is manually tested and approved by QA team
- [ ] All existing acceptance tests are still up-to-date
- [ ] New feature/change is covered by Daedalus Testing scenario
- [ ] All existing Daedalus Testing scenarios are still up-to-date

### After Review

- [ ] Update Slack QA thread by marking it with a green checkmark

2022-10-19 14:46 UTC, gabriela-ponce commented
@VanessaPC Here are a few issues/inconsistencies on this PR:

- When you click on "Security" and "Wallets", you are redirected to the tab "General". Check [this](https://drive.google.com/file/d/1QQsT0KtHGQ94d4-VVoUK9HGnetF4iVjm/view?usp=sharing) video.
- Not sure if this one is on the scope of this task, but when you enable discreet mode, the "eye" icon doesn't change (it should be crossed out), additionally, when you click on it there is an error on the screen. Check [this](https://drive.google.com/file/d/1tN0w5LU6bTo4LfKGPkX629mdGCCuckmO/view?usp=sharing) video.

2022-10-24 21:27 UTC, szymonmaslowski requested changes
Nice work! Just two small comments ;)

2022-10-24 21:27 UTC, szymonmaslowski commented on storybook/stories/settings/general/General.stories.tsx
>  const changeControl = (name: string, value: boolean) => {
It looks like this guy is no longer used. Please remove it.

2022-10-24 21:27 UTC, szymonmaslowski commented on storybook/stories/settings/general/General.stories.tsx
> +const onValueChange = (
It looks like the `StoryStore`, `mockedGeneralState` and the `onValueChange` are copied over from another story, right? Let's extract them to a separate file and import them in all the places ;) This file could be placed in the `stories/settings/utils` directory. I would also suggest naming them in common a way to reflect their purpose, for example: `LanguageSettingsStore`, `languageSettingsInitialState`, `onLanguageSettingsChange`.

2022-10-25 09:30 UTC, szymonmaslowski approved these changes
👍

2022-10-25 10:35 UTC, szymonmaslowski commented on storybook/stories/settings/general/General.stories.tsx
> +const onValueChange = (
Right, that makes sense 🙂

2022-10-25 12:01 UTC, dmitrii-gaico approved these changes

2022-10-26 12:03 UTC, miorsufianiohk approved these changes
LGTM. Great work @VanessaPC 👍

2022-10-26 12:27 UTC, ManusMcCole approved these changes
👍

2022-10-26 12:34 UTC, gabriela-ponce approved these changes

2022-10-26 12:36 UTC, merged