Create CODE-OF-CONDUCT.md
input-output-hk/daedalus pull request #3074
Opened 2022-11-03 16:44 UTC by Trueblueaddie

This is a requested document for all repos. It follows a standard format.

2022-11-10 11:29 UTC, michalrus requested changes
@Trueblueaddie this is not the newest Code of Conduct (v2.1), instead it is v1.4 (further outdated, missing a few changes from current v1.4).

See also:
* the discussion in https://input-output-rnd.slack.com/archives/CR599HMFX/p1667499355637769
* the PR to CEH → https://github.com/input-output-hk/cardano-engineering-handbook/pull/42
* up-to-date CoC (as of 2022-11-10) → https://github.com/input-output-hk/cardano-engineering-handbook/blob/8f8586f44229f57561fc99fb3ffa5a9c2ae1be1f/CODE-OF-CONDUCT.md

Also, @abailly-iohk suggested this should be a link to `cardano-engineering-handbook` rather than a full file copy.

2023-01-07 13:14 UTC, Trueblueaddie commented
Modified to direct to CEH. Sorry for the delay.

2023-01-09 11:43 UTC, michalrus approved these changes

2023-01-10 10:58 UTC, michalrus commented on CODE-OF-CONDUCT.md
> +See https://github.com/input-output-hk/cardano-engineering-handbook/blob/main/CODE-OF-CONDUCT.md
I think so, yeah, it would also be similar to other repos under `input-output-hk` then

2023-01-10 11:26 UTC, DominikGuzei approved these changes

2023-01-11 15:14 UTC, merged