[DDW-1221] Remove Chromatic from project
input-output-hk/daedalus pull request #3126
Opened 2023-06-09 08:36 UTC by DominikGuzei

This PR removes any trace of Chromatic from the codebase.

2023-06-12 10:40 UTC, michalrus approved these changes
Thank you!

2023-06-13 10:09 UTC, marcin-mazurek requested changes

2023-06-13 10:11 UTC, dmitrii-gaico approved these changes

2023-06-13 10:34 UTC, marcin-mazurek approved these changes

2023-06-13 13:57 UTC, merged